---
abstract: "Generate POD documentation during \"make\" time"
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Differences: 0
  Test::More: 0.70
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Generated
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::ISA: 0
  Devel::Peek: 0
  Devel::Symdump: 0
  Module::Install::Template: 0
  Template: 0
  Text::Conjunct: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Pod-Generated
  homepage: http://search.cpan.org/dist/Pod-Generated/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/pod-generated.git
version: 0.05
